[package]
name = "ulmas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
regex = "1.7.0"
tokio = { version = "1", features = ["full"] }
